# Generated by Django 5.1.6 on 2026-01-10 10:05

from django.db import migrations, models

import honduras_shop_aggregator.image_utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_preferred_delivery_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='users/placeholder.jpg', help_text='Upload JPEG or PNG image up to 15MB.', null=True, upload_to=honduras_shop_aggregator.image_utils.image_upload_path, validators=[honduras_shop_aggregator.image_utils.validate_image]),
        ),
    ]
