# Generated by Django 5.1.6 on 2025-04-13 05:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(error_messages={'unique': 'A store with that name already exists.'}, max_length=255, unique=True, verbose_name='store_name')),
                ('website', models.URLField(error_messages={'unique': 'A store with that website already exists.'}, unique=True, verbose_name='website')),
                ('is_verified', models.BooleanField(default=False)),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller',
            },
        ),
    ]
