# Generated by Django 5.1.6 on 2025-04-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='store_name',
            field=models.CharField(error_messages={'unique': 'A store with that name already exists.'}, max_length=255, unique=True, verbose_name='store name'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='website',
            field=models.URLField(error_messages={'unique': 'A store with that website already exists.'}, help_text='Start with http:// or https://', unique=True, verbose_name='website'),
        ),
    ]
