# Generated by Django 5.1.6 on 2025-04-14 09:16

from django.db import migrations

import honduras_shop_aggregator.sellers.models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_alter_seller_store_name_alter_seller_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='website',
            field=honduras_shop_aggregator.sellers.models.HttpsURLField(error_messages={'unique': 'A store with that website already exists.'}, help_text='Start with http:// or https://', unique=True, verbose_name='website'),
        ),
    ]
