# Generated by Django 5.1.6 on 2025-04-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_alter_seller_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.TextField(blank=True, help_text='A short description of your store.', verbose_name='description'),
        ),
    ]
