# Generated by Django 5.1.6 on 2026-05-13 14:10

from django.db import migrations, models

import honduras_shop_aggregator.image_utils


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_seller_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload JPEG or PNG image up to 15MB.', null=True, upload_to=honduras_shop_aggregator.image_utils.image_upload_path, validators=[honduras_shop_aggregator.image_utils.validate_image]),
        ),
    ]
