# Generated by Django 5.1.6 on 2026-05-16 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('sellers', '0005_seller_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sellers', to='cities.city'),
        ),
    ]
