# Generated by Django 5.1.6 on 2026-05-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('sellers', '0006_seller_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='delivery_cities',
            field=models.ManyToManyField(blank=True, help_text='Cities where this seller usually delivers products.', related_name='default_delivery_sellers', to='cities.city', verbose_name='Default delivery cities'),
        ),
    ]
