# Generated by Django 5.1.6 on 2026-05-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0007_seller_delivery_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
