# Generated by Django 5.1.6 on 2026-09-07 13:01

from django.db import migrations

import honduras_shop_aggregator.sellers.models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0008_seller_deleted_at_seller_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='website',
            field=honduras_shop_aggregator.sellers.models.HttpsURLField(error_messages={'unique': 'A store with that website or social media already exists.'}, help_text='Add your store website or a public Instagram/Facebook page.', unique=True, verbose_name='Website or social media'),
        ),
    ]
