# Generated by Django 5.1.6 on 2025-04-27 15:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import honduras_shop_aggregator.products.models
import honduras_shop_aggregator.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0004_seller_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='product name')),
                ('product_link', honduras_shop_aggregator.products.models.HttpsURLField(blank=True, error_messages={'unique': 'This product is already listed.'}, help_text='Start with http:// or https://', unique=True, verbose_name='product link')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Description of the product.', verbose_name='description')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, default='products/placeholder.png', help_text='Upload JPEG or PNG image up to 2MB.', null=True, upload_to='products/<function image_upload_path at 0x7d3ab6744310>', validators=[honduras_shop_aggregator.utils.validate_image])),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_products', to='sellers.seller')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Users_liked')),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
    ]
