# Generated by Django 5.1.6 on 2025-04-27 16:14

from django.db import migrations, models

import honduras_shop_aggregator.utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/placeholder.png', help_text='Upload JPEG or PNG image up to 2MB.', null=True, upload_to=honduras_shop_aggregator.utils.image_upload_path, validators=[honduras_shop_aggregator.utils.validate_image]),
        ),
    ]
