# Generated by Django 5.1.6 on 2025-05-05 10:30

from django.db import migrations

import honduras_shop_aggregator.products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_link',
            field=honduras_shop_aggregator.products.models.HttpsURLField(blank=True, error_messages={'unique': 'This product is already listed.'}, help_text='Start with http:// or https://', null=True, unique=True, verbose_name='product link'),
        ),
    ]
