# Generated by Django 5.1.6 on 2025-07-01 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('products', '0006_remove_product_user_product_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_cities',
            field=models.ManyToManyField(blank=True, related_name='delivery_products', to='cities.city', verbose_name='Cities available for delivery'),
        ),
        migrations.AddField(
            model_name='product',
            name='origin_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='origin_products', to='cities.city', verbose_name='City of the product'),
        ),
    ]
