# Generated by Django 5.1.6 on 2025-07-01 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('products', '0007_product_delivery_cities_product_origin_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='origin_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_products', to='cities.city', verbose_name='City of the product'),
        ),
    ]
