# Generated by Django 5.1.6 on 2025-08-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_deleted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_added'], 'verbose_name': 'Product'},
        ),
    ]
