# Generated by Django 5.1.6 on 2026-01-10 10:05

from django.db import migrations, models

import honduras_shop_aggregator.image_utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/placeholder.png', help_text='Upload JPEG or PNG image up to 15MB.', null=True, upload_to=honduras_shop_aggregator.image_utils.image_upload_path, validators=[honduras_shop_aggregator.image_utils.validate_image]),
        ),
    ]
