# Generated by Django 5.1.6 on 2026-07-17 23:02

import django.db.models.deletion
from django.db import migrations, models

import honduras_shop_aggregator.image_utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload JPEG or PNG image up to 15MB.', upload_to=honduras_shop_aggregator.image_utils.image_upload_path, validators=[honduras_shop_aggregator.image_utils.validate_image])),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='products.product')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
