# Generated by Django 5.1.6 on 2026-07-26 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_type', models.CharField(choices=[('size', 'Size'), ('color', 'Color'), ('material', 'Material'), ('style', 'Style'), ('capacity', 'Capacity'), ('weight', 'Weight'), ('pattern', 'Pattern'), ('other', 'Other')], max_length=20)),
                ('custom_type', models.CharField(blank=True, help_text="Required only when 'Other' is selected.", max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
