# Generated by Django 5.1.6 on 2026-08-13 20:42

from django.contrib.postgres.operations import (TrigramExtension,
                                                UnaccentExtension)
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_productimage_order_productvariation'),
    ]

    operations = [
        UnaccentExtension(),
        TrigramExtension(),
    ]
