# Generated by Django 5.1.6 on 2026-09-01 12:52

from django.db import migrations, models

import honduras_shop_aggregator.image_utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20260813_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload JPEG or PNG image up to 15MB.', null=True, upload_to=honduras_shop_aggregator.image_utils.image_upload_path, validators=[honduras_shop_aggregator.image_utils.validate_image]),
        ),
    ]
