# Generated by Django 5.1.6 on 2026-09-15 12:37

from django.conf import settings
from django.db import migrations, models

import honduras_shop_aggregator.products.models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options'),
        ('cities', '0001_initial'),
        ('products', '0016_alter_product_image'),
        ('sellers', '0009_alter_seller_website'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_link',
            field=honduras_shop_aggregator.products.models.HttpsURLField(blank=True, help_text='Start with http:// or https://', null=True, verbose_name='product link'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('product_link',), name='unique_active_product_link'),
        ),
    ]
